name: msgphp-ci
recipe: custom

services:
  appserver:
    type: php:7.2

tooling:
  php:
    service: appserver
    description: Run PHP commands
    cmd: php
  composer:
    service: appserver
    description: Run Composer commands
    cmd: composer
  run:
    service: appserver
    description: Run any command
    cmd: ~
