name: msgphp-ci
recipe: custom

services:
  appserver:
    type: php:7.1

tooling:
  php:
    service: appserver
    description: Run PHP commands
    cmd:
      - php
  composer:
    service: appserver
    description: Run Composer commands
    cmd:
      - composer
  bash:
    service: appserver
    description: Run bash commands
    cmd:
      - bash
      - -xc
